apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hwsw-workshop-pr-
  namespace: default
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/codefactoryhu/hwsw-workshop-20220524.git
    - name: gitRevision
      value: master
    - name: imageUrl
      value: ghcr.io/codefactoryhu/picalc
    - name: imageTag
      value: v1.0.2
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc

